#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: point jTicket sync at a Supabase project.
#
# Sync rides Supabase Realtime Broadcast: both machines open one outbound WSS
# connection to <project>.supabase.co and join a broadcast topic named by the
# share's room id. Nothing is deployed to Supabase — no functions, no tables,
# no SQL — so this wizard only creates a project (path 1) or takes one you
# already have (path 2), then wires its URL and publishable key into
# .data/jticket/sync.json. jTicket reads that file fresh, so a running app
# picks it up without a restart.
#
# BOTH machines must point at the SAME Supabase project: a broadcast topic
# only exists within one project, so two projects means two rooms that never
# meet. The second machine runs this wizard and chooses option 2.
#
# The key wired here is the publishable (anon) key — the one meant to ship in
# browsers. It grants nothing but the right to join a topic, and frames are
# sealed with the share's room secret before they leave the machine, so
# Supabase relays ciphertext it cannot read. Never wire the secret/service_role
# key here; jTicket has no use for it.
# ──────────────────────────────────────────────────────────────────────────

RELAY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$RELAY_DIR/../.." && pwd)"
DATA_DIR="${JSUITE_DATA_DIR:-$ROOT/.data}"
SYNC_FILE="$DATA_DIR/jticket/sync.json"
JTICKET="${JTICKET_URL:-http://localhost:43000}"

mkdir -p "$DATA_DIR/jticket"
# Re-run memory (ask/write_env) lives next to the config it produces.
ENV_FILE="$DATA_DIR/jticket/relay-wizard.env"

die() { warn "$1"; exit 1; }

TOTAL_STAGES=5 # the create path; the wire-only path trims this after the choice

banner "jTicket sync — Supabase relay"

# ── Stage 1: which run is this? ───────────────────────────────────────────
stage "Choose your path"
say "jTicket sync needs a Supabase project to relay through. Nothing gets"
say "deployed into it — sync only uses Realtime Broadcast, which is on by"
say "default. The free plan is plenty."
say ""
say "One of you creates the project; then BOTH machines wire the same one."
say ""
say "  1) Create a new Supabase project"
say "  2) Wire a project that already exists (you have its URL and key)"
ask WIZ_PATH "1 or 2:"
JOIN=""
case "$WIZ_PATH" in
  1) ;;
  2) JOIN=1; TOTAL_STAGES=3 ;;
  *) die "answer 1 or 2" ;;
esac

if [[ -z "$JOIN" ]]; then
  # ── Stage 2: create the project ─────────────────────────────────────────
  stage "Create the Supabase project"
  say "Sign in (GitHub works), then create a project. Any name; pick the"
  say "region closest to the two of you — every sync frame round-trips"
  say "through it."
  step "Create a new project and wait for it to finish provisioning (~2 min)."
  open_url "https://supabase.com/dashboard/projects"
  pause "Press Enter once the project is up."

  # ── Stage 3: copy the credentials ───────────────────────────────────────
  stage "Copy the project's URL and key"
  say "In the project: Settings → API Keys (or Project Settings → API)."
  step "Copy the Project URL — https://<ref>.supabase.co"
  step "Copy the publishable key (labelled 'anon' on older dashboards)."
  say ""
  warn "NOT the secret / service_role key — jTicket never needs it."
  ask SUPABASE_URL "Project URL:"
  ask SUPABASE_KEY "Publishable (anon) key:"
else
  # ── Stage 2 (wire-only): the credentials to wire ────────────────────────
  stage "The project's URL and key"
  say "Ask whoever created the project for its URL and publishable key —"
  say "both machines must use the same project, or your rooms never meet."
  ask SUPABASE_URL "Project URL (https://<ref>.supabase.co):"
  ask SUPABASE_KEY "Publishable (anon) key:"
fi

[[ -n "${SUPABASE_URL:-}" ]] || die "no project URL — nothing to wire"
[[ -n "${SUPABASE_KEY:-}" ]] || die "no publishable key — nothing to wire"
SUPABASE_URL="${SUPABASE_URL%/}"
[[ "$SUPABASE_URL" =~ ^https?:// ]] || die "that doesn't look like a URL: $SUPABASE_URL"

# ── Verify: the project must actually relay before it gets wired ──────────
stage "Verify the relay"
say "Broadcasting a probe frame through $SUPABASE_URL …"
# Realtime's REST broadcast endpoint takes the same messages the websocket
# does, so a 202 proves the URL, the key and Realtime itself are all good —
# without opening a socket. The probe topic is nobody's room and the payload
# is meaningless; no listener, nothing stored.
PROBE_CODE=$(curl -sS -o /tmp/jticket-relay-probe.$$ -w '%{http_code}' --max-time 15 \
  -X POST "$SUPABASE_URL/realtime/v1/api/broadcast" \
  -H "apikey: $SUPABASE_KEY" \
  -H 'content-type: application/json' \
  --data '{"messages":[{"topic":"jticket-wizard-probe","event":"frame","payload":{},"private":false}]}' \
  2>/dev/null) || PROBE_CODE="000"
PROBE_BODY=$(cat "/tmp/jticket-relay-probe.$$" 2>/dev/null || true)
rm -f "/tmp/jticket-relay-probe.$$"
if [[ "$PROBE_CODE" == "2"* ]]; then
  printf '  %s✓ Supabase relayed the probe%s (HTTP %s) — nothing left behind\n' "$GREEN" "$RESET" "$PROBE_CODE"
elif [[ "$PROBE_CODE" == "401" || "$PROBE_CODE" == "403" ]]; then
  warn "Supabase rejected the key (HTTP $PROBE_CODE)."
  note "  Check you copied the publishable/anon key, not a secret key."
  confirm "Wire these values anyway?" || die "not wiring an unverified project"
else
  warn "the probe did not succeed (HTTP $PROBE_CODE):"
  note "  ${PROBE_BODY:-<no response>}"
  confirm "Wire these values anyway?" || die "not wiring an unverified project"
fi

# ── Wire: land the credentials where jTicket reads them ───────────────────
stage "Wire jTicket"
node -e '
const fs = require("fs"), path = require("path")
const [file, url, key] = process.argv.slice(1)
let cfg = {}
try {
  const parsed = JSON.parse(fs.readFileSync(file, "utf8"))
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) cfg = parsed
} catch {}
cfg.supabaseUrl = url
cfg.supabaseKey = key
// The Cloudflare worker this replaced. Leaving it behind would only confuse
// the next reader — jTicket ignores it either way.
delete cfg.relayUrl
fs.mkdirSync(path.dirname(file), { recursive: true })
fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + "\n")
' "$SYNC_FILE" "$SUPABASE_URL" "$SUPABASE_KEY" || die "could not write $SYNC_FILE"
printf '  %s✓ wrote%s supabaseUrl + supabaseKey → %s\n' "$GREEN" "$RESET" "$SYNC_FILE"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_KEY "$SUPABASE_KEY"

LIVE=$(curl -s --max-time 2 "$JTICKET/api/sync/relay" 2>/dev/null) || true
if [[ "${LIVE:-}" == *'"configured":true'* && "${LIVE:-}" == *"$SUPABASE_URL"* ]]; then
  say "jTicket is running and already sees the relay — no restart needed."
elif [[ "${LIVE:-}" == *'"configured"'* ]]; then
  # The endpoint answered but with another URL — only an env var can shadow
  # the file we just wrote.
  warn "jTicket is running but reports a different relay — JTICKET_SUPABASE_URL"
  warn "or JTICKET_SYNC_RELAY_URL overrides sync.json; unset it and restart."
else
  note "jTicket isn't running (or predates /api/sync/relay) — sync.json is"
  note "read fresh, so this lands as soon as a current build is up."
fi
say ""
say "Your coworker's machine must wire the SAME project:"
note "  they run packages/relay/wizard.sh, choose option 2, and paste:"
note "  $SUPABASE_URL"
note "  (and the same publishable key)"
# ──────────────────────────────────────────────────────────────────────────

finish
