#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: deploy the jTicket sync signaling relay and wire jTicket to it.
#
# The relay (src/worker.mjs) is a Cloudflare Worker + Durable Object that
# ferries opaque WebRTC handshake blobs between the two peers of a share; it
# never sees project data. One of the two coworkers deploys it once (path 1);
# then BOTH machines wire the same URL into .data/jticket/sync.json (path 2
# is the wire-only run for the second machine). jTicket reads the file fresh,
# so a running app picks the URL up without a restart.
# ──────────────────────────────────────────────────────────────────────────

RELAY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$RELAY_DIR/../.." && pwd)"
DATA_DIR="${JSUITE_DATA_DIR:-$ROOT/.data}"
SYNC_FILE="$DATA_DIR/jticket/sync.json"
JTICKET="${JTICKET_URL:-http://localhost:43000}"

mkdir -p "$DATA_DIR/jticket"
# Re-run memory (ask/write_env) lives next to the config it produces.
ENV_FILE="$DATA_DIR/jticket/relay-wizard.env"

die() { warn "$1"; exit 1; }

# wrangler however it's available: a real install first (also how the test
# stubs it), else fetched on the fly.
run_wrangler() {
  if command -v wrangler >/dev/null 2>&1; then wrangler "$@"
  elif command -v pnpm >/dev/null 2>&1; then pnpm dlx wrangler "$@"
  else npx -y wrangler "$@"
  fi
}

TOTAL_STAGES=6 # the deploy path; the wire-only path trims this after the choice

banner "jTicket sync — signaling relay"

# ── Stage 1: which run is this? ───────────────────────────────────────────
stage "Choose your path"
say "jTicket sync needs a signaling relay: a tiny Cloudflare Worker both"
say "machines use to exchange WebRTC handshakes. It never sees project data."
say "One of you deploys it once; then BOTH machines wire the same URL."
say ""
say "  1) Deploy a new relay to my Cloudflare account"
say "  2) Wire a relay that's already deployed (you have its URL)"
ask WIZ_PATH "1 or 2:"
JOIN=""
case "$WIZ_PATH" in
  1) ;;
  2) JOIN=1; TOTAL_STAGES=4 ;;
  *) die "answer 1 or 2" ;;
esac

if [[ -z "$JOIN" ]]; then
  # ── Stage 2: Cloudflare account ─────────────────────────────────────────
  stage "Cloudflare account"
  say "The relay deploys as a Worker with one Durable Object — Cloudflare's"
  say "free plan covers it (SQLite-backed DO; no card needed)."
  step "Sign in to the Cloudflare dashboard, or create a free account."
  open_url "https://dash.cloudflare.com/"
  pause "Press Enter once you're signed in."

  # ── Stage 3: authorize wrangler ─────────────────────────────────────────
  stage "Authorize wrangler"
  say "wrangler is Cloudflare's deploy CLI; it deploys from packages/relay/."
  if WHOAMI=$(run_wrangler whoami 2>&1) && [[ "$WHOAMI" != *"not authenticated"* ]]; then
    note "already authorized — wrangler whoami answered."
  else
    step "A browser tab opens — click 'Allow' to authorize wrangler."
    run_wrangler login || die "wrangler login failed — re-run the wizard to retry"
    run_wrangler whoami >/dev/null 2>&1 || die "wrangler still isn't authorized"
  fi

  # ── Stage 4: deploy ─────────────────────────────────────────────────────
  stage "Deploy the relay worker"
  say "Deploying the 'jsuite-relay' worker (wrangler.jsonc)…"
  DEPLOY_LOG=$(mktemp)
  if ! (cd "$RELAY_DIR" && run_wrangler deploy 2>&1 | tee "$DEPLOY_LOG"); then
    die "wrangler deploy failed — fix the error above and re-run the wizard"
  fi
  DETECTED=$(grep -oE 'https://[A-Za-z0-9._-]+\.workers\.dev' "$DEPLOY_LOG" | head -1 || true)
  if [[ -n "$DETECTED" ]]; then
    say "Detected the deployed URL from the output:"
    write_env RELAY_URL "$DETECTED"
  else
    step "Copy the https://…workers.dev URL from the deploy output above."
  fi
  ask RELAY_URL "Relay URL:"
else
  # ── Stage 2 (wire-only): the URL to wire ────────────────────────────────
  stage "The relay URL"
  say "Ask whoever deployed the relay for its URL — both machines must use"
  say "the same one, or your rooms will never meet."
  ask RELAY_URL "Relay URL (https://…workers.dev):"
fi

[[ -n "${RELAY_URL:-}" ]] || die "no relay URL — nothing to wire"
RELAY_URL="${RELAY_URL%/}"
[[ "$RELAY_URL" =~ ^https?:// ]] || die "that doesn't look like a URL: $RELAY_URL"

# ── Verify: the relay must actually answer before it gets wired ───────────
stage "Verify the relay"
say "Minting (and immediately killing) a probe room on $RELAY_URL …"
PROBE=$(curl -sS --max-time 10 -X POST "$RELAY_URL/rooms" -H 'content-type: application/json' -d '{}' 2>&1) || true
if [[ "${PROBE:-}" == *'"roomId"'* ]]; then
  ROOM_ID=$(sed -n 's/.*"roomId":"\([^"]*\)".*/\1/p' <<<"$PROBE")
  ROOM_SECRET=$(sed -n 's/.*"secret":"\([^"]*\)".*/\1/p' <<<"$PROBE")
  if [[ -n "$ROOM_ID" && -n "$ROOM_SECRET" ]]; then
    curl -sS --max-time 10 -X DELETE "$RELAY_URL/rooms/$ROOM_ID?secret=$ROOM_SECRET" >/dev/null 2>&1 || true
  fi
  printf '  %s✓ relay answered%s — probe room minted and killed, nothing left behind\n' "$GREEN" "$RESET"
else
  warn "the relay at $RELAY_URL did not answer with a room:"
  note "  ${PROBE:-<no response>}"
  confirm "Wire this URL anyway?" || die "not wiring an unverified relay URL"
fi

# ── Wire: land the URL where jTicket reads it ─────────────────────────────
stage "Wire jTicket"
node -e '
const fs = require("fs"), path = require("path")
const [file, url] = process.argv.slice(1)
let cfg = {}
try {
  const parsed = JSON.parse(fs.readFileSync(file, "utf8"))
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) cfg = parsed
} catch {}
cfg.relayUrl = url
fs.mkdirSync(path.dirname(file), { recursive: true })
fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + "\n")
' "$SYNC_FILE" "$RELAY_URL" || die "could not write $SYNC_FILE"
printf '  %s✓ wrote%s relayUrl → %s\n' "$GREEN" "$RESET" "$SYNC_FILE"
write_env RELAY_URL "$RELAY_URL"

LIVE=$(curl -s --max-time 2 "$JTICKET/api/sync/relay" 2>/dev/null) || true
if [[ "${LIVE:-}" == *'"configured":true'* && "${LIVE:-}" == *"$RELAY_URL"* ]]; then
  say "jTicket is running and already sees the relay — no restart needed."
elif [[ "${LIVE:-}" == *'"configured"'* ]]; then
  # The endpoint answered but with another URL — only an env var can shadow
  # the file we just wrote.
  warn "jTicket is running but reports a different relay — a JTICKET_RELAY_URL"
  warn "env var overrides sync.json; unset it or restart without it."
else
  note "jTicket isn't running (or predates /api/sync/relay) — sync.json is"
  note "read fresh, so this lands as soon as a current build is up."
fi
say ""
say "Your coworker's machine must wire the SAME relay URL:"
note "  they run packages/relay/wizard.sh, choose option 2, and paste:"
note "  $RELAY_URL"
# ──────────────────────────────────────────────────────────────────────────

finish
